export default {
    loading: true,
    header: true,
    colgroup: true,
    caption: false,
    captionText: 'captionText',
    useClassName: false,
    className: '',
    styles: [
        {
            selector: 'tbody>tr>:nth-child(1)',
            styles: 'text-align: left',
        },
    ],
    columnSettings: [
        {
            useWidth: false,
            width: 0,
            widthUnits: 'px',
            align: 'none',
        },
        {
            useWidth: false,
            width: 0,
            widthUnits: 'px',
            align: 'none',
        },
        {
            useWidth: false,
            width: 0,
            widthUnits: 'px',
            align: 'none',
        },
        {
            useWidth: false,
            width: 0,
            widthUnits: 'px',
            align: 'none',
        },
    ],
    colgroupProps: [
        {
            span: 1,
        },
        {
            span: 1,
        },
        {
            span: 1,
        },
        {
            span: 1,
        },
    ],
    headerContent: [
        {
            innerHTML: 'innerHTML',
            rowspan: 1,
            colspan: 1,
            rowCollision: false,
            colCollision: false,
        },
        {
            innerHTML: 'innerHTML',
            rowspan: 1,
            colspan: 1,
            rowCollision: false,
            colCollision: false,
        },
        {
            innerHTML: 'innerHTML',
            rowspan: 1,
            colspan: 1,
            rowCollision: false,
            colCollision: false,
        },
        {
            innerHTML: 'innerHTML',
            rowspan: 1,
            colspan: 1,
            rowCollision: false,
            colCollision: false,
        },
    ],

    content: [
        [
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
        ],
        [
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
        ],
        [
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
        ],
    ],
};
