export default {
    loading: true,
    header: true,
    footer: true,
    colgroup: true,
    caption: false,
    captionText: 'captionText',
    useClassName: false,
    className: '',
    styles: [
        {
            selector: 'tbody>tr>:nth-child(1)',
            style: 'text-align: left',
        },
    ],
    columnSettings: [
        {
            useWidth: false,
            width: 0,
            widthUnits: 'px',
            align: 'none',
        },
        {
            useWidth: false,
            width: 0,
            widthUnits: 'px',
            align: 'none',
        },
        {
            useWidth: false,
            width: 0,
            widthUnits: 'px',
            align: 'none',
        },
    ],
    colgroupProps: [
        {
            useSpan: false,
            span: 1,
            useClassName: false,
            className: '',
        },
        {
            useSpan: false,
            span: 1,
            useClassName: false,
            className: '',
        },
        {
            useSpan: false,
            span: 1,
            useClassName: false,
            className: '',
        },
    ],
    headerContent: [
        [
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
        ],
    ],

    content: [
        [
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
        ],
        [
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
        ],
    ],
    footerContent: [
        [
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
                isHeader: false,
                headerScope: 'col',
            },
        ],
    ],
};
