export default {
    loading: true,
    header: true,
    caption: false,
    captionText: 'captionText',
    headerContent: [
        {
            innerHTML: 'innerHTML',
            rowspan: 1,
            colspan: 1,
            rowCollision: false,
            colCollision: false,
        },
        {
            innerHTML: 'innerHTML',
            rowspan: 1,
            colspan: 1,
            rowCollision: false,
            colCollision: false,
        },
        {
            innerHTML: 'innerHTML',
            rowspan: 1,
            colspan: 1,
            rowCollision: false,
            colCollision: false,
        },
        {
            innerHTML: 'innerHTML',
            rowspan: 1,
            colspan: 1,
            rowCollision: false,
            colCollision: false,
        },
        {
            innerHTML: 'innerHTML',
            rowspan: 1,
            colspan: 1,
            rowCollision: false,
            colCollision: false,
        },
    ],

    content: [
        [
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
        ],
        [
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
        ],
        [
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
        ],
        [
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
            {
                innerHTML: 'innerHTML',
                rowspan: 1,
                colspan: 1,
                rowCollision: false,
                colCollision: false,
            },
        ],
    ],
};
